### ISSUE TITLE
Doc Fix: Document suggest some other package name

### ISSUE THREAD

**Issue by mitulgolakiya** [rentshare/rentshare-php#1]
The documentation over here: https://developer.placepay.com/?php#introduction says,

`composer require place/place-php:master`.

But seems like, the package name is, `placepay/place-php` in the [composer.json](https://github.com/placepay/place-php/blob/master/composer.json#L2)

But seems like readme has the correct version. I don't found where to submit it to docs website, so just posting it here.

**Comment by ianhalpern** [comment]
Good eye, thanks! The README and composer.json file have been updated.
